### ISSUE TITLE
Error in swapNodesWithoutSwappingData.cpp

### ISSUE THREAD

**Issue by S1xe** [mandliya/algorithms_and_data_structures#5]
https://github.com/mandliya/algorithms_and_data_structures/blob/4c27c33d166844e3479ff1c6a67e68877bc331dc/linked_list_problems/swapNodesWithoutSwappingData.cpp#L63

It should be `head = currx;`.

While use following code,it will be a mistake.
```c++
int main() {
  Node *head = nullptr;
  insert(head, 10);
  insert(head, 15);
  insert(head, 12);
  insert(head, 13);
  insert(head, 20);
  insert(head, 14);
  printList(head);//10-->15-->12-->13-->20-->14-->null
  // std::cout << "Replacing 12 with 20 and 20 with 12:\n";
  swapSpecial(head, 15, 10);
  printList(head);//10-->12-->13-->20-->14-->null

  return 0;
}
```

The whole code is in https://wandbox.org/permlink/reP9TwPiXXWeMsw0

**Comment by AnayMehrotra** [comment]
Can you elaborate on the issue?

**Comment by S1xe** [comment]
@AnayMehrotra 
We can easily find the node `15` is removed while use the code.But it should be `15-->10-->12-->13-->20-->14-->null`.

**Comment by HarshitNagar** [comment]
will submit a pr
