### ISSUE TITLE
Error in binarySearchTree.h

### ISSUE THREAD

**Issue by S1xe** [mandliya/algorithms_and_data_structures#6]
#### 1.__findMin and __findMax
They are declared as:
https://github.com/mandliya/algorithms_and_data_structures/blob/e3636067119eab91ba1687551d6c9e2ebfd7a812/include/binarySearchTree.h#L51-L52
And,they are invoked as:
https://github.com/mandliya/algorithms_and_data_structures/blob/e3636067119eab91ba1687551d6c9e2ebfd7a812/include/impl/binarySearchTree.impl.h#L74
So,it's should be as follow:
```c++
            const BinaryNode *  __findMin( BinaryNode *node ) const;
            const BinaryNode * __findMax( BinaryNode *node ) const;
```

#### 2.height with __height
https://github.com/mandliya/algorithms_and_data_structures/blob/e3636067119eab91ba1687551d6c9e2ebfd7a812/include/binarySearchTree.h#L43
https://github.com/mandliya/algorithms_and_data_structures/blob/e3636067119eab91ba1687551d6c9e2ebfd7a812/include/binarySearchTree.h#L61

The function `__height` should be declare as `const int __height( BinaryNode * node ) const; `

**Comment by HarshitNagar** [comment]
will submit a pr soon
